### ISSUE TITLE
Paramdex

### ISSUE THREAD

**Issue by TruE-DarKMatteR** [vawser/ER-Documentation#3]
I don't know if this was intentional or because of X or Y reason. But the "Paramdex" folder that usualy is in \ER-Documentation-main\ER-Documentation-main -->"Paramdex" is not there in this latest .ZIP and just wanted to let you know. 
If you already are aware of this--> Disregard current message and have a nice day : )

**Comment by vawser** [comment]
I removed it since the changes are now part of the DSMS. Any future changes will be via a pull request to DSMS, so I thought it best not to host an older version of Paramdex within the repository.

**Comment by TruE-DarKMatteR** [comment]
👍
